version: '3.4'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
      target: production
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app/
volumes:
  dbdata:
